#!/bin/bash

echo "ArtisenAlley Deployment to UBCO Server"
echo "===================================="
echo ""
echo "STEP 1: Make sure you're connected to myvpn.ok.ubc.ca if off-campus"
echo ""
echo "STEP 2: Connect to the server and set up your project"
echo "Run these commands:"
echo ""
echo "  ssh qrehman@cosc360.ok.ubc.ca"
echo ""
echo "Once logged in, run these commands:"
echo ""
echo "  # Navigate to public_html folder"
echo "  cd public_html"
echo ""
echo "  # Remove old code if it exists"
echo "  rm -rf ArtisenAlley"
echo ""
echo "  # Clone the repository"
echo "  git clone https://github.com/abdur026/ArtisenAlley.git"
echo ""
echo "  # Set proper permissions"
echo "  chmod -R 775 ArtisenAlley"
echo ""
echo "  # Set the production flag to true"
echo "  sed -i 's/\$is_production = false;/\$is_production = true;/' ArtisenAlley/config/db.php"
echo ""
echo ""
echo "STEP 3: Set up your database"
echo "Run these commands after SSH login:"
echo ""
echo "  # Connect to MySQL"
echo "  mysql -u qrehman -p"
echo ""
echo "  # When prompted, enter your password (initially 'qrehman')"
echo ""
echo "  # In MySQL prompt, run:"
echo "  use qrehman;"
echo ""
echo "  # Import the database schema"
echo "  source ~/public_html/ArtisenAlley/db_setup.sql;"
echo ""
echo "  # Exit MySQL"
echo "  exit;"
echo ""
echo "STEP 4: Test your deployment"
echo "Visit: https://cosc360.ok.ubc.ca/qrehman/ArtisenAlley/public/server_test.php"
echo ""
echo "STEP 5: Access your website"
echo "Your website should be available at: https://cosc360.ok.ubc.ca/qrehman/ArtisenAlley/public/"
echo ""
echo "NOTE: If images don't show up, make sure your image paths are correct!"
