#!/bin/bash

echo "ArtisenAlley Deployment to UBCO Server"
echo "===================================="
echo ""
echo "STEP 1: Make sure you're connected to myvpn.ok.ubc.ca if off-campus"
echo ""
echo "STEP 2: Connect to the server and set up your project"
echo "Run these commands:"
echo ""
echo "  ssh qrehman@cosc360.ok.ubc.ca"
echo ""
echo "Once logged in, run these commands:"
echo ""
echo "  # Navigate to public_html folder"
echo "  cd public_html"
echo ""
echo "  # Remove old code if it exists"
echo "  rm -rf ArtisenAlley"
echo ""
echo "  # Clone the repository (make sure you're on the server branch)"
echo "  git clone -b server https://github.com/abdur026/ArtisenAlley.git"
echo ""
echo "  # Set proper permissions"
echo "  chmod -R 775 ArtisenAlley"
echo "  chmod -R 775 ArtisenAlley/public/images/products"
echo ""
echo ""
echo "STEP 3: Set up your database"
echo "Run these commands after SSH login:"
echo ""
echo "  # Connect to MySQL"
echo "  mysql -u qrehman -p"
echo ""
echo "  # When prompted, enter your password (initially 'qrehman')"
echo ""
echo "  # In MySQL prompt, run:"
echo "  use qrehman;"
echo ""
echo "  # Check for existing tables"
echo "  show tables;"
echo ""
echo "  # Drop existing tables if there are issues (CAUTION! THIS DELETES DATA!)"
echo "  # Only run these if you need to start fresh:"
echo "  SET FOREIGN_KEY_CHECKS = 0;"
echo "  DROP TABLE IF EXISTS users, products, orders, order_items, reviews, cart;"
echo "  SET FOREIGN_KEY_CHECKS = 1;"
echo ""
echo "  # Import the database schema"
echo "  source ~/public_html/ArtisenAlley/db_setup.sql;"
echo ""
echo "  # Verify tables were created"
echo "  show tables;"
echo ""
echo "  # Exit MySQL"
echo "  exit;"
echo ""
echo "STEP 4: Verify database connection"
echo "Visit: https://cosc360.ok.ubc.ca/qrehman/ArtisenAlley/public/url_debug.php"
echo ""
echo "STEP 5: Check for common issues:"
echo "  - Incorrect database password (default is your CWL, which is 'qrehman')"
echo "  - Missing tables in the database"
echo "  - Incorrect BASE_URL in paths.php (should be '/qrehman/ArtisenAlley/public')"
echo "  - File permissions issues (images folder should be writable)"
echo ""
echo "STEP 6: Accessing phpMyAdmin to manage your database"
echo "Visit: https://cosc360.ok.ubc.ca/phpmyadmin/"
echo "Username: qrehman"
echo "Password: Your MySQL password (initially 'qrehman')"
echo ""
echo "STEP 7: Test your deployment"
echo "Visit: https://cosc360.ok.ubc.ca/qrehman/ArtisenAlley/public/server_test.php"
echo ""
echo "STEP 8: Access your website"
echo "Your website should be available at: https://cosc360.ok.ubc.ca/qrehman/ArtisenAlley/public/"
echo ""
echo "Troubleshooting Tips:"
echo "1. If you see database errors:"
echo "   - Check if the database tables exist using phpMyAdmin"
echo "   - Try running the db_setup.sql script again"
echo "   - Verify your database credentials in config/db.php"
echo ""
echo "2. If images don't display:"
echo "   - Check image paths in the database (should be relative paths)"
echo "   - Ensure the images folder has proper permissions"
echo ""
echo "3. If login/register pages don't work:"
echo "   - Check URL path generation in config/paths.php"
echo "   - Use url_debug.php to verify URL generation"
echo ""
echo "For more help, visit the URL debug tool: https://cosc360.ok.ubc.ca/qrehman/ArtisenAlley/public/url_debug.php"
