<?php
// URL Debug Script
// This script helps diagnose URL generation issues on the UBCO server

// Include paths configuration
require_once '../config/paths.php';

echo "<html><head><title>ArtisenAlley URL Path Debugger</title>";
echo "<style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
    .container { border: 1px solid #ddd; padding: 15px; margin-bottom: 20px; border-radius: 4px; }
    h1 { color: #333; } 
    h2 { color: #555; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
    pre { background: #f5f5f5; padding: 10px; border-radius: 4px; overflow: auto; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { text-align: left; padding: 8px; border-bottom: 1px solid #ddd; }
    th { background-color: #f2f2f2; }
    .url-test { margin-bottom: 10px; padding: 8px; border-radius: 4px; background-color: #f8f8f8; }
</style>";
echo "</head><body>";

echo "<h1>ArtisenAlley URL Path Debugger</h1>";
echo "<p>Use this script to diagnose URL generation issues on the UBCO server.</p>";

// Display server information
echo "<div class='container'>";
echo "<h2>Server Information</h2>";
echo "<table>";
echo "<tr><th>Variable</th><th>Value</th></tr>";
echo "<tr><td>SERVER_NAME</td><td>" . htmlspecialchars($_SERVER['SERVER_NAME'] ?? 'Not set') . "</td></tr>";
echo "<tr><td>REQUEST_URI</td><td>" . htmlspecialchars($_SERVER['REQUEST_URI'] ?? 'Not set') . "</td></tr>";
echo "<tr><td>SCRIPT_NAME</td><td>" . htmlspecialchars($_SERVER['SCRIPT_NAME'] ?? 'Not set') . "</td></tr>";
echo "<tr><td>PHP_SELF</td><td>" . htmlspecialchars($_SERVER['PHP_SELF'] ?? 'Not set') . "</td></tr>";
echo "<tr><td>DOCUMENT_ROOT</td><td>" . htmlspecialchars($_SERVER['DOCUMENT_ROOT'] ?? 'Not set') . "</td></tr>";
echo "<tr><td>SCRIPT_FILENAME</td><td>" . htmlspecialchars($_SERVER['SCRIPT_FILENAME'] ?? 'Not set') . "</td></tr>";
echo "<tr><td>SERVER_SOFTWARE</td><td>" . htmlspecialchars($_SERVER['SERVER_SOFTWARE'] ?? 'Not set') . "</td></tr>";
echo "</table>";
echo "</div>";

// Display paths configuration
echo "<div class='container'>";
echo "<h2>Paths Configuration</h2>";
echo "<table>";
echo "<tr><th>Variable</th><th>Value</th></tr>";
echo "<tr><td>BASE_URL</td><td>" . htmlspecialchars(defined('BASE_URL') ? BASE_URL : 'Not defined') . "</td></tr>";
echo "<tr><td>is_ubco_server</td><td>" . ($is_ubco_server ? 'True' : 'False') . "</td></tr>";
echo "</table>";
echo "</div>";

// Test URL generation
echo "<div class='container'>";
echo "<h2>URL Generation Tests</h2>";

// Array of paths to test
$test_paths = [
    '/login.php',
    'login.php',
    '/index.php',
    'index.php',
    '/product.php?id=1',
    '',
    '/'
];

echo "<table>";
echo "<tr><th>Path Input</th><th>Generated URL</th><th>Full URL</th></tr>";

foreach ($test_paths as $path) {
    $generated_url = url($path);
    $full_url = 'https://' . ($_SERVER['SERVER_NAME'] ?? 'localhost') . $generated_url;
    
    echo "<tr>";
    echo "<td><code>" . htmlspecialchars($path) . "</code></td>";
    echo "<td><code>" . htmlspecialchars($generated_url) . "</code></td>";
    echo "<td><a href='" . htmlspecialchars($full_url) . "' target='_blank'>" . htmlspecialchars($full_url) . "</a></td>";
    echo "</tr>";
}
echo "</table>";
echo "</div>";

// Examine header links
echo "<div class='container'>";
echo "<h2>Navigation Links Test</h2>";
echo "<p>The following links would be generated by the header.php file:</p>";

$nav_links = [
    'Home' => url('/index.php'),
    'Explore' => url('/search.php?keyword='),
    'Login' => url('/login.php'),
    'Register' => url('/register.php'),
    'Cart' => url('/cart.php'),
    'Profile' => url('/profile.php'),
    'Logout' => url('/logout.php')
];

echo "<table>";
echo "<tr><th>Link Name</th><th>Generated URL</th><th>Test Link</th></tr>";

foreach ($nav_links as $name => $url) {
    echo "<tr>";
    echo "<td>" . htmlspecialchars($name) . "</td>";
    echo "<td><code>" . htmlspecialchars($url) . "</code></td>";
    echo "<td><a href='" . htmlspecialchars($url) . "' target='_blank'>Test " . htmlspecialchars($name) . " Link</a></td>";
    echo "</tr>";
}
echo "</table>";
echo "</div>";

// Recommendations
echo "<div class='container'>";
echo "<h2>Recommendations</h2>";
echo "<p>Based on testing:</p>";
echo "<ul>";
echo "<li>Make sure paths.php is correctly detecting the UBCO server environment</li>";
echo "<li>Ensure the BASE_URL is set to '/qrehman/ArtisenAlley/public' for the UBCO server</li>";
echo "<li>Check that all links in header.php use the leading slash (e.g., url('/login.php'))</li>";
echo "<li>Verify that the .htaccess file (if used) is not affecting URL rewrites</li>";
echo "</ul>";

echo "<p>To update the paths.php file on the server:</p>";
echo "<pre>
// Example paths.php configuration
if (strpos(\$_SERVER['SERVER_NAME'], 'cosc360.ok.ubc.ca') !== false) {
    define('BASE_URL', '/qrehman/ArtisenAlley/public');
} else {
    define('BASE_URL', '');
}

function url(\$path) {
    \$path = ltrim(\$path, '/');
    if (!empty(\$path)) {
        return BASE_URL . '/' . \$path;
    } else {
        return BASE_URL;
    }
}
</pre>";
echo "</div>";

echo "</body></html>";
?>
